version: 2.1

orbs:
  terraform: escaletech/terraform@0.4
  gh-release: escaletech/gh-conventional-release@0.1

workflows:
  version: 2
  ci:
    jobs:
      - tf-check:
          filters:
            branches: { ignore: master }
            tags: { ignore: /.*/ }
  release:
    jobs:
      - gh-release/create-release:
          context: github-create-release
          continue-on-error: true
          filters:
            branches: { ignore: /.*/ }
            tags: { only: /^v.*/ }
