version: 2.1

orbs:
  terraform: escaletech/terraform@0.4
  gh-release: escaletech/gh-conventional-release@0.1

jobs:
  tf-check:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pre-commit
            pre-commit install
            curl https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
            tflint --init
      - terraform/install-terraform
      - run:
          name: Terraform checks
          command: pre-commit run --all-files

workflows:
  version: 2
  ci:
    jobs:
      - tf-check:
          filters:
            branches: { ignore: master }
            tags: { ignore: /.*/ }
  release:
    jobs:
      - gh-release/create-release:
          context: github-create-release
          continue-on-error: true
          filters:
            branches: { ignore: /.*/ }
            tags: { only: /^v.*/ }
