version: 2.1

orbs:
  terraform: circleci/terraform@1.1
  gh-release: escaletech/gh-conventional-release@0.1

workflows:
  version: 2
  ci:
    jobs:
      - terraform/fmt:
          <<: &tf-ci
            checkout: true
            matrix:
              parameters:
                path: [
                  "modules/cdn",
                  "modules/mysql",
                  "modules/sqs_queue" ,
                  "modules/rds_postgres"
                ]
          filters:
            &ci-filters {
              branches: { ignore: master },
              tags: { ignore: /.*/ }
            }
      - terraform/validate:
          <<: *tf-ci
          filters: *ci-filters

  dev:
    jobs:
      - terraform/fmt:
          <<: *tf-ci
          filters:
            &dev-filters {
              branches: { only: master },
              tags: { ignore: /.*/ }
            }
      - terraform/validate:
          <<: *tf-ci
          filters: *dev-filters

  release:
    jobs:
      - gh-release/create-release:
          filters:
            &release-filters {
              branches: { ignore: /.*/ },
              tags: { only: /v.+/ }
            }
